{"name": "Test duplicate courier creation", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'уже существует' in 'Этот логин уже используется. Попробуйте другой.'", "trace": "self = <tests.test_courier.TestCourier object at 0x000001E04C506C10>\n\n    @allure.title(\"Test duplicate courier creation\")\n    def test_create_duplicate_courier(self):\n        courier_data = register_new_courier_and_return_login_password()\n        login, password, first_name = courier_data\n    \n        response = CourierApi.create_courier(login, password, first_name)\n    \n        assert response.status_code == 409\n>       assert \"уже существует\" in response.json()[\"message\"]\nE       AssertionError: assert 'уже существует' in 'Этот логин уже используется. Попробуйте другой.'\n\ntests\\test_courier.py:28: AssertionError"}, "start": 1758386124059, "stop": 1758386124843, "uuid": "8e2743a0-beed-4677-9d60-65bfde4c467f", "historyId": "5ad5b15bf3963f6e235835a0c0c284c2", "testCaseId": "5ad5b15bf3963f6e235835a0c0c284c2", "fullName": "tests.test_courier.TestCourier#test_create_duplicate_courier", "labels": [{"name": "feature", "value": "Courier API"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier"}, {"name": "subSuite", "value": "TestCourier"}, {"name": "host", "value": "HOME-PC"}, {"name": "thread", "value": "16380-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier"}]}