{"name": "Принятие заказа с несуществующим ID заказа", "status": "broken", "statusDetails": {"message": "AttributeError: type object 'ExpectedResponses' has no attribute 'ORDER_NOT_EXIST'", "trace": "self = <tests.test_accept_order.TestAcceptOrder object at 0x00000284B95B4A70>, setup_courier_and_order = {'courier_id': 615725, 'login': 'zdvmgrkdtk', 'order_id': 546572, 'password': 'xknrvlvzhl', ...}\n\n    @allure.title(\"Принятие заказа с несуществующим ID заказа\")\n    @allure.severity(allure.severity_level.NORMAL)\n    def test_accept_order_invalid_order_id(self, setup_courier_and_order):\n        with allure.step(\"Попытаться принять несуществующий заказ\"):\n            response = OrderApi.accept_order(\n                \"9999999999\",\n                setup_courier_and_order[\"courier_id\"]\n            )\n    \n        with allure.step(\"Проверить ошибку ненайденного заказа\"):\n>           assert response.status_code == ExpectedResponses.ORDER_NOT_EXIST[\"code\"]\nE           AttributeError: type object 'ExpectedResponses' has no attribute 'ORDER_NOT_EXIST'\n\ntests\\test_accept_order.py:73: AttributeError"}, "steps": [{"name": "Попытаться принять несуществующий заказ", "status": "passed", "steps": [{"name": "Принять заказ '9999999999' курьером 615725", "status": "passed", "parameters": [{"name": "order_id", "value": "'9999999999'"}, {"name": "courier_id", "value": "615725"}], "start": 1758527537246, "stop": 1758527537621}], "start": 1758527537246, "stop": 1758527537621}, {"name": "Проверить ошибку ненайденного заказа", "status": "broken", "statusDetails": {"message": "AttributeError: type object 'ExpectedResponses' has no attribute 'ORDER_NOT_EXIST'\n", "trace": "  File \"C:\\Users\\Пользователь\\sprint_7\\tests\\test_accept_order.py\", line 73, in test_accept_order_invalid_order_id\n    assert response.status_code == ExpectedResponses.ORDER_NOT_EXIST[\"code\"]\n"}, "start": 1758527537621, "stop": 1758527537621}], "start": 1758527537246, "stop": 1758527537622, "uuid": "cff5afc4-bab2-46c8-bfcb-abbba37b9367", "historyId": "e4f726252d51a7f0f084ca15b11fa1cc", "testCaseId": "e4f726252d51a7f0f084ca15b11fa1cc", "fullName": "tests.test_accept_order.TestAcceptOrder#test_accept_order_invalid_order_id", "labels": [{"name": "epic", "value": "Order Management"}, {"name": "severity", "value": "normal"}, {"name": "feature", "value": "Accept Order API"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_accept_order"}, {"name": "subSuite", "value": "TestAcceptOrder"}, {"name": "host", "value": "HOME-PC"}, {"name": "thread", "value": "9396-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_accept_order"}]}