{"name": "Test accept order with invalid order id", "status": "failed", "statusDetails": {"message": "AssertionError: assert 500 == 404\n +  where 500 = <Response [500]>.status_code", "trace": "self = <tests.test_accept_order.TestAcceptOrder object at 0x000001E04C59C5F0>\n\n    @allure.title(\"Test accept order with invalid order id\")\n    def test_accept_order_invalid_order_id(self):\n        response = OrderApi.accept_order(\"9999999999\", self.courier_id)\n    \n>       assert response.status_code == 404\nE       assert 500 == 404\nE        +  where 500 = <Response [500]>.status_code\n\ntests\\test_accept_order.py:61: AssertionError"}, "start": 1758386122470, "stop": 1758386122870, "uuid": "bbc28c61-37b2-4c54-ab3a-d254cbe48adb", "historyId": "e4f726252d51a7f0f084ca15b11fa1cc", "testCaseId": "e4f726252d51a7f0f084ca15b11fa1cc", "fullName": "tests.test_accept_order.TestAcceptOrder#test_accept_order_invalid_order_id", "labels": [{"name": "feature", "value": "Accept Order API"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_accept_order"}, {"name": "subSuite", "value": "TestAcceptOrder"}, {"name": "host", "value": "HOME-PC"}, {"name": "thread", "value": "16380-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_accept_order"}]}